name: finc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  expense_repository:
    path: packages/expense_repository
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  fl_chart: ^0.66.0
  intl: ^0.19.0
  http: ^0.13.4
  firebase_core: ^2.16.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  cloud_firestore: ^4.15.5
  uuid: ^4.3.1 
  flutter_colorpicker: ^1.0.3
  google_sign_in: ^6.1.5
  firebase_auth: ^4.17.4
  flutter_multi_formatter: ^2.7.0
  flutter_speed_dial: ^7.0.0
  math_expressions: ^2.1.0
  google_speech: ^2.2.0
  path_provider: ^2.0.11
  cached_network_image: ^3.3.1
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  flutter_localizations:
      sdk: flutter
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/iconedoapp.png"
