name: finc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  expense_repository:
    path: packages/expense_repository
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.0.1-dev
  font_awesome_flutter: ^10.8.0
  fl_chart: ^0.66.0
  intl: ^0.20.2
  http: ^0.13.4

  # Firebase - versões compatíveis com Core 3.x
  firebase_core: ^3.15.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.4.10
  firebase_messaging: ^15.2.10

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  uuid: ^4.5.1
  flutter_colorpicker: ^1.0.3
  google_sign_in: ^6.1.5
  flutter_multi_formatter: ^2.7.0
  flutter_speed_dial: ^7.0.0
  math_expressions: ^2.1.0
  google_speech: ^2.2.0
  path_provider: ^2.0.11
  cached_network_image: ^3.3.1
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  flutter_localizations:
    sdk: flutter
  file_picker: ^8.0.7
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  month_picker_dialog: ^6.0.3
  smooth_page_indicator: ^1.1.0
  pie_chart: 5.4.0
  share_plus: ^10.0.0
  flutter_local_notifications: ^17.2.0
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1



flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/iconedoapp.png"
